chore(android): accurate naming score and score values
logto-io/kotlin pull request #50
Opened 2021-11-22 11:33 UTC by IceHe

## Summary

- Naming score and score values accurately. 

- Definitions

    - `scope value` : one of `openid`, `name`, `email` & etc.

    - `scope values` : array/list/set consisted of multiple `scope value`s

        - e.g. `["openid", "name", "email"]`

    - `scope` : the string consisted of `scope value`s joined by whitespace

        - a non-normative example of a scope Request: `scope=openid profile email phone`

        _from https://www.rfc-editor.org/rfc/inline-errata/rfc6749.html session 3.3_

        > The value of the scope parameter is expressed as a space-delimited list of case-sensitive strings.
        
- References : https://openid.net/specs/openid-connect-basic-1_0.html#Scopes

## Linear Issue Reference

## Testing

Pass all existing tests.

2021-11-22 11:51 UTC, gao-sun requested changes
scope not score?

2021-11-22 11:54 UTC, IceHe commented
> scope not score?

`scope`. I will fix the typos.

2021-11-23 02:48 UTC, xiaoyijun approved these changes
LGTM

2021-11-23 03:14 UTC, wangsijie approved these changes
LGTM

2021-11-23 04:28 UTC, xiaoyijun requested changes
branch name must follow our naming convention: [naming convention](https://www.notion.so/silverhand/Development-Guideline-d1f37ae3f6ef4842a5c629411f8a2ed7#5b34ded69c3e4b5f89e38fc38c1591bd)

2021-11-23 04:39 UTC, closed without merging

2021-11-23 04:41 UTC, IceHe commented
> branch name must follow our naming convention: [naming convention](https://www.notion.so/silverhand/Development-Guideline-d1f37ae3f6ef4842a5c629411f8a2ed7#5b34ded69c3e4b5f89e38fc38c1591bd)

Thx~ I rename the branch to `icehe-renaming-scope`.